
initial_popn <- array(rpois(n = 24, lambda = 100),
                      dim = c(4, 2, 3),
                      dimnames = list(age = c("0-4", "5-9", "10-14", "15+"),
                                      sex = c("Female", "Male"),
                                      region = c("A", "B", "C")))
fertility_rates <- array(runif(240, max = c(0, 0, 2, 0)),
                         dim = c(4, 2, 2, 3, 5),
                         dimnames = list(age = c("0-4", "5-9", "10-14", "15+"),
                                         triangle = c("Lower", "Upper"),
                                         sex = c("Female", "Male"),
                                         region = c("A", "B", "C"),
                                         time = c("2001-2005", "2006-2010",
                                                  "2011-2015", "2016-2020",
                                                  "2021-2025")))
mortality_rates <- array(runif(240, max = c(0.05, 0.1, 0.1, 0.3)),
                         dim = c(4, 2, 2, 3, 5),
                         dimnames = list(age = c("0-4", "5-9", "10-14", "15+"),
                                         triangle = c("Lower", "Upper"),
                                         sex = c("Female", "Male"),
                                         region = c("A", "B", "C"),
                                         time = c("2001-2005", "2006-2010",
                                                  "2011-2015", "2016-2020",
                                                  "2021-2025")))
internal_rates <- array(runif(720, max = 0.2),
                        dim = c(4, 2, 2, 3, 3, 5),
                        dimnames = list(age = c("0-4", "5-9", "10-14", "15+"),
                                        triangle = c("Lower", "Upper"),
                                        sex = c("Female", "Male"),
                                        region_orig = c("A", "B", "C"),
                                        region_dest = c("A", "B", "C"),
                                        time = c("2001-2005", "2006-2010",
                                                 "2011-2015", "2016-2020",
                                                 "2021-2025")))
internal_rates[slice.index(internal_rates, 4) == slice.index(internal_rates, 5)] <- 0
immigration_means <- array(rpois(n = 240, lambda = 15),
                           dim = c(4, 2, 2, 3, 5),
                           dimnames = list(age = c("0-4", "5-9", "10-14", "15+"),
                                           triangle = c("Lower", "Upper"),
                                           sex = c("Female", "Male"),
                                           region = c("A", "B", "C"),
                                           time = c("2001-2005", "2006-2010",
                                                    "2011-2015", "2016-2020",
                                                    "2021-2025")))
emigration_rates <- array(runif(n = 240, max = 0.1),
                          dim = c(4, 2, 2, 3, 5),
                          dimnames = list(age = c("0-4", "5-9", "10-14", "15+"),
                                          triangle = c("Lower", "Upper"),
                                          sex = c("Female", "Male"),
                                          region = c("A", "B", "C"),
                                          time = c("2001-2005", "2006-2010",
                                                   "2011-2015", "2016-2020",
                                                   "2021-2025")))
ans_obtained <- micro:::microsim(initial_popn = initial_popn,
                         fertility_rates = fertility_rates,
                         mortality_rates = mortality_rates,
                         internal_rates = internal_rates,
                         immigration_means = immigration_means,
                         emigration_rates = emigration_rates,
                         step_length = 5,
                         dominant_sex = "Female")
a <- Movements(population = Counts(ans_obtained$popn),
               births = subarray(Counts(ans_obtained$births), age == "10-14", drop = FALSE),
               internal = Counts(ans_obtained$internal),
               entries = list(immigration = Counts(ans_obtained$immigration)),
               exits = list(deaths = Counts(ans_obtained$deaths),
                            emigration = Counts(ans_obtained$emigration)))
summary(a)
