// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// make_time_remaining_bd
double make_time_remaining_bd(int step_length, bool is_lower, bool is_final_age);
RcppExport SEXP _micro_make_time_remaining_bd(SEXP step_lengthSEXP, SEXP is_lowerSEXP, SEXP is_final_ageSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type step_length(step_lengthSEXP);
    Rcpp::traits::input_parameter< bool >::type is_lower(is_lowerSEXP);
    Rcpp::traits::input_parameter< bool >::type is_final_age(is_final_ageSEXP);
    rcpp_result_gen = Rcpp::wrap(make_time_remaining_bd(step_length, is_lower, is_final_age));
    return rcpp_result_gen;
END_RCPP
}
// micro_bd
List micro_bd(IntegerVector initial_popn, NumericVector fert_rates, NumericVector mort_rates, int n_age, int n_sex, int n_period, int n_iter, int step_length, int i_dom_sex);
RcppExport SEXP _micro_micro_bd(SEXP initial_popnSEXP, SEXP fert_ratesSEXP, SEXP mort_ratesSEXP, SEXP n_ageSEXP, SEXP n_sexSEXP, SEXP n_periodSEXP, SEXP n_iterSEXP, SEXP step_lengthSEXP, SEXP i_dom_sexSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type initial_popn(initial_popnSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type fert_rates(fert_ratesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mort_rates(mort_ratesSEXP);
    Rcpp::traits::input_parameter< int >::type n_age(n_ageSEXP);
    Rcpp::traits::input_parameter< int >::type n_sex(n_sexSEXP);
    Rcpp::traits::input_parameter< int >::type n_period(n_periodSEXP);
    Rcpp::traits::input_parameter< int >::type n_iter(n_iterSEXP);
    Rcpp::traits::input_parameter< int >::type step_length(step_lengthSEXP);
    Rcpp::traits::input_parameter< int >::type i_dom_sex(i_dom_sexSEXP);
    rcpp_result_gen = Rcpp::wrap(micro_bd(initial_popn, fert_rates, mort_rates, n_age, n_sex, n_period, n_iter, step_length, i_dom_sex));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_micro_make_time_remaining_bd", (DL_FUNC) &_micro_make_time_remaining_bd, 3},
    {"_micro_micro_bd", (DL_FUNC) &_micro_micro_bd, 9},
    {NULL, NULL, 0}
};

RcppExport void R_init_micro(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
