# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

make_time_remaining_bd <- function(step_length, is_lower, is_final_age) {
    .Call(`_micro_make_time_remaining_bd`, step_length, is_lower, is_final_age)
}

micro_bd <- function(initial_popn, fert_rates, mort_rates, n_age, n_sex, n_period, n_iter, step_length, i_dom_sex) {
    .Call(`_micro_micro_bd`, initial_popn, fert_rates, mort_rates, n_age, n_sex, n_period, n_iter, step_length, i_dom_sex)
}

